#ifndef DEFINE_H
#define DEFINE_H

#include <stdio.h>
#include <stdlib.h>

//INTERFACE / TEXTO
#define LINHA_SEPARADORA "________________________________\n"
#define COMANDO_SAIDA 9
#define TAM_DESCRICAO_LOG 200
#define TAM_NOME_FICHEIRO 150
#define TAM_DATA_HORA_FORMATADA 30

//LIMITES DE STRINGS
#define MAX_ID_PRODUTO 16
#define MAX_ID_COLABORADOR 16
#define MAX_NOME 60
#define MAX_NOME_PRODUTO 60

//FICHEIROS PADRAO
#define PASTA_ASSETS "src/assets/"
#define FICHEIRO_CLIENTES PASTA_ASSETS "clientes.txt"
#define FICHEIRO_PRODUTOS PASTA_ASSETS "produtos.txt"
#define FICHEIRO_COLABORADORES PASTA_ASSETS "colaboradores.txt"
#define FICHEIRO_CONFIGURACAO PASTA_ASSETS "configuracao.txt"
#define PASTA_RELATORIOS "relatorios/"
#define PREFIXO_FICHEIRO_HISTORICO "Historico_"
#define PREFIXO_FICHEIRO_ESTATISTICAS "Estatisticas_simulacao_"
#define EXTENSAO_TXT ".txt"
#define EXTENSAO_CSV ".csv"

//CAPACIDADES INICIAIS
#define CAPACIDADE_INICIAL_CLIENTES_BASE 64
#define CAPACIDADE_INICIAL_PRODUTOS_BASE 64
#define CAPACIDADE_INICIAL_COLABORADORES_BASE 16
#define CAPACIDADE_INICIAL_LOGS 128
#define CAPACIDADE_INICIAL_HISTORICO_CLIENTES_CAIXA 16
//Foi escolhido um número primo de buckets para melhorar a distribuição dos clientes na tabela hash e reduzir colisões. Como a tabela usa 
//encadeamento, mesmo que existam colisões, os clientes ficam organizados numa lista dentro do bucket correspondente.
#define HASH_N_BUCKETS_INICIAL 101

//CRESCIMENTO DINAMICO
#define FATOR_CRESCIMENTO_VETORES 2

//SIMULACAO
#define MAX_ESPERA_DEFAULT 120
#define N_CAIXAS_DEFAULT 6
#define MAX_PRECO_DEFAULT 40.0f
#define MAX_FILA_DEFAULT 7
#define MIN_FILA_DEFAULT 3
#define CICLO_SIMULACAO_MINUTOS 1
#define MIN_NOVOS_CLIENTES_POR_CICLO_DEFAULT 0
#define MAX_NOVOS_CLIENTES_POR_CICLO_DEFAULT 2
#define MAX_PRODUTOS_CLIENTE_DEFAULT 20
#define MIN_PRODUTOS_CLIENTE_DEFAULT 1
#define DIFERENCA_TEMPO_CAIXAS_DEFAULT 20
#define VELOCIDADE_SIMULACAO_1X 1
#define VELOCIDADE_SIMULACAO_5X 5
#define VELOCIDADE_SIMULACAO_10X 10
#define VELOCIDADE_SIMULACAO_100X 100
#define VELOCIDADE_SIMULACAO_500X 500
#define VELOCIDADE_SIMULACAO_DEFAULT VELOCIDADE_SIMULACAO_100X
#define SLEEP_SIMULACAO_BASE_MS 500
#define CICLOS_POR_REFRESH_TELA 60
#define MAX_CLIENTES_MERCADO 500

//CAIXAS
#define N_CAIXAS_INICIALMENTE_ABERTAS 1
#define N_MINIMO_CLIENTES_CAIXAS 3
#define ID_CAIXA_INVALIDO -1
#define PREFIXO_FICHEIRO_CAIXA "Caixa_"
#define PREFIXO_FICHEIRO_HISTORICO "Historico_"
#define PREFIXO_FICHEIRO_ESTATISTICAS "Estatisticas_simulacao_"

//CLIENTES / ESTADOS
#define CLIENTE_NAO_RECEBEU_OFERTA 0
#define CLIENTE_RECEBEU_OFERTA 1
#define CLIENTE_NAO_MUDOU_DE_FILA 0
#define CLIENTE_JA_MUDOU_DE_FILA 1
#define CLIENTE_NAO_PODE_MUDAR_DE_FILA 0
#define CLIENTE_PODE_MUDAR_DE_FILA 1

//CONTROLO DE CAIXA
#define CAIXA_SEM_CONTROLO_MANUAL 0
#define CAIXA_COM_CONTROLO_MANUAL 1
#define CAIXA_NAO_BLOQUEADA_AUTOMATICAMENTE 0
#define CAIXA_BLOQUEADA_AUTOMATICAMENTE 1

//VALORES SENTINELA
#define INDICE_INVALIDO -1
#define VALOR_FLOAT_INVALIDO -1.0f

//FORMATOS DE EXPORTACAO
#define CABECALHO_CSV_HISTORICO "instante;descricao\n"
#define CABECALHO_CSV_PERFORMANCE "funcao;tempo_ms\n"

//MEMORIA / DIAGNOSTICO
#define MEMORIA_ZERO 0UL

#endif